# Generated by Django 3.0.7 on 2020-07-02 02:38

from django.db import migrations
from data_files.categories import categories

def create_categories(apps, schema_editor):
    Category = apps.get_model('books', 'Category')
    for category_name in categories:
        Category.objects.create(name=category_name)

class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200702_0159'),
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]
