# Generated by Django 3.0.7 on 2020-07-02 03:47

from django.db import migrations
from django.utils.text import slugify

class Migration(migrations.Migration):

    def create_slugs(apps, schema_editor):
        Category = apps.get_model('books', 'Category')
        categories = Category.objects.all()
        for category in categories:
            category.slug = slugify(category.name)
            category.save()


    dependencies = [
        ('books', '0006_auto_20200702_0344'),
    ]

    operations = [
        migrations.RunPython(create_slugs)
        
    ]
